### ISSUE TITLE
Fehlerhafte HTML-Code im Ausgabeformat HTML

### ISSUE THREAD

**Issue by 31er** [psi-4ward/mooquee4ward#1]
Mit Contao 2.11.5 wird bei Verwendung des Ausgabeformat HTML fehlerhafter Code erzeugt, was zur Fehlfunktion führt. Slider ohne Funktion, Layout wird zerschossen.

Erzeugt wird:
<div class="mooquee block" id="mooquee53>

Korrekt wäre:
<div class="mooquee block" id="mooquee53">

Das schließende " fehlt.

Wird als Ausgabeformat XHTML verwendet, ist alles korrekt und funktioniert bestens.

**Comment by 31er** [comment]
Sorry, meine ersten github-Erfahrungen. Die HTML-Tags wurden nicht übernommen und ich weiß nicht, wie man HTML-Tags hier posten kann.

Bei der ID mooquee wird das letzte " nicht vergeben id="mooquee53
Korrekt wäre "mooquee53"

**Comment by psi-4ward** [comment]
fixed in 8932feddf821896b0fdde1bc481c876ad026e517
