### ISSUE TITLE
.htaccess missing in /html

### ISSUE THREAD

**Issue by fritzmg** [psi-4ward/mooquee4ward#5]
The subfolder `/html` is missing an .htaccess file with the following content:

``` php
<IfModule !mod_authz_core.c>
  Order allow,deny
  Allow from all
</IfModule>
<IfModule mod_authz_core.c>
  Require all granted
</IfModule>
```

Without it, Mooquee1.1.js cannot be loaded.

Btw. is this the right repository? I notice that there is a version 3.0.0 released on the ER2, however, this repository only has releasees up to 2.4.0.

**Comment by psi-4ward** [comment]
Mooquee is deprecated and dead.
Let me know if you want to adopt the repo.
